### ISSUE TITLE
feature request: make submodules public

### ISSUE THREAD

**Issue by faysou** [nakashima-hikaru/implied-vol#1]
Hello,

Would it be possible to make your submodules public ? Like in the below. 
I would like to reuse some of your functions in sub modules.

Thank you.

```
mod erf_cody;
mod normal_distribution;
mod rational_cubic;
pub(crate) mod lets_be_rational;
pub(crate) mod bachelier;
pub(crate) mod constants;
```

**Comment by nakashima-hikaru** [comment]
This was handled by adding feature flags.
If this does not satisfy your request, please let me know.

**Comment by faysou** [comment]
Thank you sir.
